# LSTM to Seq2Seq
- I will try to use medical examples and apply lstm or seq2seq

# LSTM
- lstm cell

![lstm](https://miro.medium.com/max/900/1*s7_EO0rjXAw99RnH1x4s_g.png)
- lstm cell takes 3 input
    - cell state from $t-1$
    - hidden state from $t-1$
    - current input $x_t$

- lstm cell output 
    - cell state from $t$
    - hidden state from $t$
    - output from $t$



In [58]:
import torch
import torch.nn as nn
import torch.nn.functional as F

use sample data

input : length 1 with 10 dimension\
output : length 1 20 dimension

In [59]:
rnn = nn.LSTM(10, 20, 1) # (input_size, hidden_size, num_layers)
input = torch.randn(1, 1, 10) # (Series Length, Batch size, input_dim)
h0 = torch.randn(1, 1, 20) # (Series Length, Batch size, input_dim)

In [60]:
rnn.input_size, rnn.hidden_size, rnn.num_layers
# input size , hidden size,  number of layers

(10, 20, 1)

In [61]:
output = rnn(input)

len(output) # length of 2

2

In [62]:
output[0], output[1]

# output 0 : 1,1,20 vector. output of layer
# output 1 : (output and the hidden output & current state output)

(tensor([[[-0.0511,  0.0860, -0.1217,  0.0877,  0.0426,  0.0022,  0.0229,
           -0.0829, -0.0583, -0.0324, -0.1867,  0.1178,  0.0094,  0.0187,
            0.0352,  0.0582, -0.0778,  0.0369,  0.0825, -0.0036]]],
        grad_fn=<StackBackward0>),
 (tensor([[[-0.0511,  0.0860, -0.1217,  0.0877,  0.0426,  0.0022,  0.0229,
            -0.0829, -0.0583, -0.0324, -0.1867,  0.1178,  0.0094,  0.0187,
             0.0352,  0.0582, -0.0778,  0.0369,  0.0825, -0.0036]]],
         grad_fn=<StackBackward0>),
  tensor([[[-0.1416,  0.1849, -0.2309,  0.1433,  0.0767,  0.0040,  0.0547,
            -0.1416, -0.1010, -0.0884, -0.4111,  0.2050,  0.0194,  0.0476,
             0.0682,  0.0931, -0.1866,  0.0725,  0.1666, -0.0062]]],
         grad_fn=<StackBackward0>)))

What if we changed the sequence of the vector to 2?

In [63]:
input = torch.rand(2, 1, 10) # sequence length 2, batch_size, 1, embedding size 10
rnn = nn.LSTM(10, 20, 1) # same model as before

In [64]:
output = rnn(input) 

output[0], output[1] 

(tensor([[[-0.0569,  0.1192, -0.0259,  0.0212, -0.0842, -0.0415, -0.1121,
            0.0661, -0.0783,  0.0848, -0.0500, -0.0435,  0.0087,  0.0822,
           -0.0447,  0.1175, -0.0532, -0.1104,  0.0928, -0.0492]],
 
         [[-0.0831,  0.1595, -0.0117,  0.0178, -0.1352, -0.0932, -0.1217,
            0.1179, -0.1499,  0.1582, -0.0862, -0.0483, -0.0161,  0.1349,
            0.0220,  0.1528, -0.0120, -0.1601,  0.1565, -0.0897]]],
        grad_fn=<StackBackward0>),
 (tensor([[[-0.0831,  0.1595, -0.0117,  0.0178, -0.1352, -0.0932, -0.1217,
             0.1179, -0.1499,  0.1582, -0.0862, -0.0483, -0.0161,  0.1349,
             0.0220,  0.1528, -0.0120, -0.1601,  0.1565, -0.0897]]],
         grad_fn=<StackBackward0>),
  tensor([[[-0.1749,  0.3374, -0.0240,  0.0464, -0.3265, -0.1827, -0.2405,
             0.2857, -0.3497,  0.3893, -0.1783, -0.0808, -0.0323,  0.2939,
             0.0380,  0.2307, -0.0278, -0.4370,  0.2883, -0.2168]]],
         grad_fn=<StackBackward0>)))

In [65]:
output[0].shape 
# The hidden state output. 

# (Length 2, batch, embed_size)

torch.Size([2, 1, 20])

In [66]:
output[1]

# (hidden state : (sequence_size, batch_size, embedding), current_state : (sequence_size, batch_size, embedding))

(tensor([[[-0.0831,  0.1595, -0.0117,  0.0178, -0.1352, -0.0932, -0.1217,
            0.1179, -0.1499,  0.1582, -0.0862, -0.0483, -0.0161,  0.1349,
            0.0220,  0.1528, -0.0120, -0.1601,  0.1565, -0.0897]]],
        grad_fn=<StackBackward0>),
 tensor([[[-0.1749,  0.3374, -0.0240,  0.0464, -0.3265, -0.1827, -0.2405,
            0.2857, -0.3497,  0.3893, -0.1783, -0.0808, -0.0323,  0.2939,
            0.0380,  0.2307, -0.0278, -0.4370,  0.2883, -0.2168]]],
        grad_fn=<StackBackward0>))

Try out bi-lstm model

In [86]:
bi_lstm = nn.LSTM(10, 20, 1, bidirectional=True)

In [87]:
output = bi_lstm(input) # input : length 2, 1 batch, size 10

In [88]:
output[0].shape 

# length 2, batch 1, 2 of 20

torch.Size([2, 1, 40])

The only difference is that the embedding becomes twice the size of the hidden output

In [93]:
layer1 = nn.LSTM(10,20,2,bidirectional=True)
layer2 = nn.LSTM(40,5,2,bidirectional=True)

class extract_tensor(nn.Module):
    def forward(self, x):
        tensor, _ = x
        return tensor

model1 = nn.Sequential(
    layer1,
    extract_tensor(),
    layer2
)

In [106]:
model1(input)[1][0]

tensor([[[ 0.0613, -0.1756, -0.0847, -0.0718, -0.1153]],

        [[ 0.1223, -0.0876,  0.0668, -0.0772,  0.0308]],

        [[-0.1749, -0.0881, -0.2084, -0.1275, -0.1554]],

        [[ 0.0212, -0.0551, -0.0744,  0.0346, -0.0522]]],
       grad_fn=<StackBackward0>)

# Bi-LSTM models with some dataset
- dataset : Tabular data - titanic

In [1]:
from pathlib import Path
import pandas as pd

project_dir = Path.cwd().parent
data_dir = project_dir.joinpath('data')

data = data_dir.joinpath('train.csv')
data = pd.read_csv(data)


In [2]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [22]:
# first tokenize all the values in the dataset
data.values

from torchtext.vocab import build_vocab_from_iterator
from collections import Counter, OrderedDict

row_wise_data = data.values.astype('str').tolist()
vocab = build_vocab_from_iterator(row_wise_data, specials = ["<unk>"])

In [49]:
from torchtext.transforms import VocabTransform, ToTensor, Sequential
import torch.nn as nn

# make vocab transform layer
vocab_transform = VocabTransform(vocab)

# get the length of the vocab and do word embedding
word_embedding = nn.Embedding(vocab.__len__(), 128)

# To tensor
transform2tensor = ToTensor()

In [51]:
my_embedding_layer = Sequential(
    vocab_transform,
    transform2tensor,
    word_embedding
)

In [124]:
 
class TableModel(nn.Module):
    
    def __init__(self, 
                 input_size,
                 hidden_size, 
                 n_layer,
                 vocab):
        super().__init__()
        
        self.vocab = vocab
        self.vocab_size = self.vocab.__len__()
        
        # embed vocab
        self.vocab_transform = VocabTransform(vocab)
        self.totensor = ToTensor()
        self.word_embedding = nn.Embedding(self.vocab_size, input_size)
        
        self.embedding_layer = Sequential(
            self.vocab_transform,
            self.totensor,
            self.word_embedding
        )
        
        # bilstm layers
        self.bilstm_layer1 = nn.LSTM(input_size=input_size,
                                     hidden_size= hidden_size, 
                                     num_layers=n_layer,
                                     bidirectional =True) 
        
        self.bilstm_layer2 = nn.LSTM(input_size= hidden_size*2,
                                     hidden_size= input_size//2,
                                     num_layers = n_layer,
                                     bidirectional=True)

        self.model = nn.Sequential(
            self.embedding_layer,
            self.bilstm_layer1,
            extract_tensor(),
            self.bilstm_layer2
        )
    
    def forward(self, x):
        output = self.model(x)
        return output
        

In [125]:
my_model = TableModel(128, 256, 2, vocab)

In [130]:
output = my_model(row_wise_data[0])

output[0].shape

torch.Size([12, 128])

# Sequence to Sequence
- 