# LSTM to Seq2Seq
- I will try to use medical examples and apply lstm or seq2seq

# LSTM
- lstm cell

![lstm](https://miro.medium.com/max/900/1*s7_EO0rjXAw99RnH1x4s_g.png)
- lstm cell takes 3 input
    - cell state from $t-1$
    - hidden state from $t-1$
    - current input $x_t$

- lstm cell output 
    - cell state from $t$
    - hidden state from $t$
    - output from $t$



In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

use sample data

input : length 1 with 10 dimension\
output : length 1 20 dimension

In [2]:
rnn = nn.LSTM(10, 20, 1) # (input_size, hidden_size, num_layers)
input = torch.randn(1, 1, 10) # (Series Length, Batch size, input_dim)
h0 = torch.randn(1, 1, 20) # (Series Length, Batch size, input_dim)

In [3]:
rnn.input_size, rnn.hidden_size, rnn.num_layers
# input size , hidden size,  number of layers

(10, 20, 1)

In [4]:
output = rnn(input)

len(output) # length of 2

2

In [39]:
hid[0], hid[1]

# hid 0 : 1,1,20 vector. output of layer
# hid 1 : output and the hidden output.

(tensor([[[-0.0132, -0.0280, -0.0658, -0.1545, -0.0591, -0.0473, -0.0345,
           -0.0801, -0.0236, -0.0128,  0.0644,  0.0250,  0.0543, -0.0052,
            0.0689,  0.1972,  0.0581, -0.0217,  0.0296,  0.0013]]],
        grad_fn=<StackBackward0>),
 (tensor([[[-0.0132, -0.0280, -0.0658, -0.1545, -0.0591, -0.0473, -0.0345,
            -0.0801, -0.0236, -0.0128,  0.0644,  0.0250,  0.0543, -0.0052,
             0.0689,  0.1972,  0.0581, -0.0217,  0.0296,  0.0013]]],
         grad_fn=<StackBackward0>),
  tensor([[[-0.0518, -0.0666, -0.1378, -0.2368, -0.0937, -0.0823, -0.0700,
            -0.1625, -0.0501, -0.0252,  0.1349,  0.0626,  0.1445, -0.0095,
             0.1098,  0.3380,  0.1332, -0.0594,  0.0631,  0.0026]]],
         grad_fn=<StackBackward0>)))

What if we changed the sequence of the vector to 2?

In [19]:
input = torch.rand(2, 1, 10) # sequence length 2, batch_size, 1, embedding size 10
rnn = nn.LSTM(10, 20, 1) # same model as before

In [20]:
output = rnn(input)

output[0], output[1]

(tensor([[[-0.0309, -0.0423,  0.1113,  0.0156, -0.0065, -0.0085, -0.0040,
           -0.0005,  0.0153, -0.0890,  0.0052, -0.0507, -0.0158, -0.1325,
           -0.1681, -0.0311, -0.0812, -0.0822,  0.0467, -0.0707],
          [-0.0585,  0.0160,  0.0479,  0.0101, -0.0034,  0.0336,  0.0124,
           -0.0171, -0.0414, -0.0824,  0.0455, -0.0525, -0.0245, -0.0968,
           -0.1602, -0.0516, -0.1210, -0.0785,  0.0693, -0.0572]]],
        grad_fn=<StackBackward0>),
 (tensor([[[-0.0309, -0.0423,  0.1113,  0.0156, -0.0065, -0.0085, -0.0040,
            -0.0005,  0.0153, -0.0890,  0.0052, -0.0507, -0.0158, -0.1325,
            -0.1681, -0.0311, -0.0812, -0.0822,  0.0467, -0.0707],
           [-0.0585,  0.0160,  0.0479,  0.0101, -0.0034,  0.0336,  0.0124,
            -0.0171, -0.0414, -0.0824,  0.0455, -0.0525, -0.0245, -0.0968,
            -0.1602, -0.0516, -0.1210, -0.0785,  0.0693, -0.0572]]],
         grad_fn=<StackBackward0>),
  tensor([[[-0.0722, -0.0787,  0.2079,  0.0371, -0.0137, -0.017

In [23]:
output[0].shape 
# The hidden state output. 
# (Length 2, batch, embed_size)

torch.Size([1, 2, 20])

In [22]:
output[0]

tensor([[[-0.0309, -0.0423,  0.1113,  0.0156, -0.0065, -0.0085, -0.0040,
          -0.0005,  0.0153, -0.0890,  0.0052, -0.0507, -0.0158, -0.1325,
          -0.1681, -0.0311, -0.0812, -0.0822,  0.0467, -0.0707],
         [-0.0585,  0.0160,  0.0479,  0.0101, -0.0034,  0.0336,  0.0124,
          -0.0171, -0.0414, -0.0824,  0.0455, -0.0525, -0.0245, -0.0968,
          -0.1602, -0.0516, -0.1210, -0.0785,  0.0693, -0.0572]]],
       grad_fn=<StackBackward0>)